### ISSUE TITLE
Password doesnt work to unlook

### ISSUE THREAD

**Issue by Karlprag** [rharel/webext-private-bookmarks#230]
Hi I use Private Bookmarks V 0.1.19

Since two days back my normal password doesn't work, I have not mad any other changes.

I use version 131.0.3 of Firefox, and I am 100% sure I have not changed or forgotten the password. 

Please advice

**Comment by Namuski** [comment]
Same here...

Only that I use 132.0 V of Firefox

I could unlock the bookmarks on the day prior and suddenly on the next day it stopped working or rather won´t accept my password. I am also pretty sure that I did not change password or anything else, since I haven´t before and saw no need for it.

Is there a way to secure the bookmarks without the password? Otherwise it seems I can´t get access and this would be reason enough for me to not use this (apart from this issue) really cool and useful plugin again.

**Comment by CandyMan1337** [comment]
Same here i had to wipe my bookmarks twice this month. Pretty annoying.

**Comment by Spring-Hiller** [comment]
The password for accessing my Firefox Private Bookmarks has stopped working. Is it possible to recover access to my Bookmarks?

**Comment by Spring-Hiller** [comment]
Has anyone received an answer concerning recovering Firefox Private BookMarks once your password quit working?

**Comment by brayStorm** [comment]
Addressed here: [https://github.com/rharel/webext-private-bookmarks/pull/244](https://github.com/rharel/webext-private-bookmarks/pull/244)

**Comment by julius3007** [comment]
> Has anyone received an answer concerning recovering Firefox Private BookMarks once your password quit working?

I contacted rharel and he told me he would be working on it during christmas hollidays.

**Comment by KurigohanSoreir** [comment]
This issue is still present and just happened to me as I lost a few months of bookmarks. Private Bookmarks keep telling me I can't unlock even though I've been using the same password since all this time.
Is there any way to retrieve the bookmark, the files or to get access to the new password the extension suddenly put itself?

Or is this extension still getting worked on?
